# Generated by Django 2.0.6 on 2018-10-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='location',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
