# Generated by Django 2.1.2 on 2018-11-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_document_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
    ]
