# Generated by Django 2.1.2 on 2018-11-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_auto_20181122_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='md5sum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
