# Generated by Django 2.1.2 on 2018-10-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='File',
        ),
    ]
