# Generated by Django 2.1.2 on 2018-10-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20181012_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
    ]
