# Generated by Django 2.1.2 on 2018-10-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_file_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
    ]
