# Generated by Django 2.1.2 on 2018-11-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20181120_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parentfolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.File'),
        ),
    ]
