# Generated by Django 2.1.2 on 2018-11-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20181120_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='picture',
            new_name='file',
        ),
    ]
