# Generated by Django 2.1.2 on 2018-11-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20181120_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
