# Generated by Django 2.1.2 on 2018-11-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20181120_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='description',
            new_name='md5sum',
        ),
    ]
