# Generated by Django 2.1.2 on 2018-11-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_auto_20181122_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='description',
            new_name='md5sum',
        ),
    ]
